### ISSUE TITLE
map_canvas & err: Minimum container dimension is 100x100 in pixels

### ISSUE THREAD

**Issue by blondie63** [mapsplugin/ionic-googlemaps-starter-tab#3]
Testing on my project i've copied similar code about map
my project was created from a ionic starter tabs
i cannot see the map, i see that map_canvas element does'nt take settings from css !

home.html:
....
  <div id="map_canvas">
    
  </div>
...

home.scss:
page-home {

    #map_canvas {
        height: 80%;
        border: 1px solid red;
      }
      
}

home.ts:
...
export class HomePage {

  map: GoogleMap;
  constructor(public navCtrl: NavController, private platform: Platform) {

  }

  ionViewDidLoad() {
    this.platform.ready().then(() => {
      console.log('ionViewDidLoad');
      this.loadMap();
    });
  }

  loadMap() {
    // Create a map after the view is loaded.
    // (platform is already ready in app.component.ts)
    this.map = GoogleMaps.create('map_canvas', {
      camera: {
        target: {
          lat: 43.0741704,
          lng: -89.3809802
        },
        zoom: 18,
        tilt: 30
      }
    });

  }
}

error:
<img width="1281" alt="maps-err-100" src="https://user-images.githubusercontent.com/1261851/44973028-74b98480-af5b-11e8-8c73-036044d11676.png">

Some help?
Thanks

**Comment by wf9a5m75** [comment]
Please share your project files(everything) on GitHub

**Comment by blondie63** [comment]
sorry for delay..
https://github.com/blondie63/tabs-cordova

**Comment by wf9a5m75** [comment]
That's css problem, not this plugin's problem.

Specify `px` instead of `%` for example.

**Comment by blondie63** [comment]
really i think the problem is not there...
i delete .git folder and run npm i and i see map but anyway the dimensions are not respected, % or px is the same.. look this attach file: 
<img width="1636" alt="maps-err dimension" src="https://user-images.githubusercontent.com/1261851/45001696-a10ee880-afcf-11e8-8a08-180a95d386cd.png">

**Comment by wf9a5m75** [comment]
This plugin does not adjust the map div size. For general programming questions about ionic, please ask at the ionic forum.

**Comment by wf9a5m75** [comment]
ping

**Comment by blondie63** [comment]
sorry for delay but a thunderbolt has destroyed my internet connection..
looking your screenshot i see that the map take the right size at your side..
very strange, but have you tried my same code ?
anyway, i don't want to waste your time, maybe the problem is in another part of code..

**Comment by wf9a5m75** [comment]
I just built your code, and run it.

**Comment by blondie63** [comment]
ok, maybe some cache problem.. i think you can close this issue..
